# Screen
TITLE = "EX-RACEONE"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
# Mixer
MUSIC_VOLUME = 0.2
SOUND_VOLUME = 0.3
# Button
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_SPACING = 20
# Loading Bar
LOADING_BAR_WIDTH = 400
LOADING_BAR_HEIGHT = 20