# Screen
TITLE = "EX-RACEONE"
SCREEN_WIDTH = 256
SCREEN_HEIGHT = 240
FPS = 60
# Mixer
MUSIC_VOLUME = 0.01
SOUND_VOLUME = 0.1
# Button
BUTTON_WIDTH = 50
BUTTON_HEIGHT = 20
BUTTON_SPACING = 10
# Loading Bar
LOADING_BAR_WIDTH = 100
LOADING_BAR_HEIGHT = 20
LOADING_BAR_MAX = 100
LOADING_BAR_STEP = 25
# Slider
SLIDER_WIDTH = 100
SLIDER_HEIGHT = 20
SLIDER_MIN = 0
SLIDER_MAX = 1